# (rule, kind, code, label)   kind: pos = rule must fire, neg = rule must NOT fire
CASES = [
# L01
("L01","pos",'dfhack.run_command("createitem", "BAR", "INORGANIC:IRON", "5")',"createitem call"),
("L01","pos",'dfhack.run_command("gui/create-item")',"gui/create-item"),
("L01","pos",'local cmd = "createitem BAR"\ndfhack.run_command(cmd)',"createitem in variable string"),
("L01","neg",'-- createitem is forbidden\nprint("ok")',"createitem in comment"),
("L01","neg",'local my_createitem_count = 0',"identifier containing createitem"),
("L01","neg",'--[[ createitem\n createitem ]]\nprint(1)',"block comment"),
("L01","neg",'print("do not use createitem")',"createitem in a message string (documentation text)"),
# L02
("L02","pos",'dfhack.run_command("dig-now")',"dig-now"),
("L02","pos",'dfhack.run_command("dignow")',"dignow"),
("L02","pos",'dfhack.run_command({"dig-now", "1","2","3"})',"dig-now table form"),
("L02","neg",'local dig_now_count = 1',"dig_now identifier"),
("L02","neg",'dfhack.run_command("digv")',"digv is a normal designation command"),
# L03
("L03","pos",'dfhack.run_command("build-now")',"build-now"),
("L03","pos",'dfhack.run_command("buildnow")',"buildnow"),
("L03","neg",'local build_nowhere = 1',"identifier"),
("L03","neg",'-- build-now',"comment"),
# L04
("L04","pos",'dfhack.run_command("reveal")',"reveal quoted"),
("L04","pos",'dfhack.run_command("reveal hell")',"reveal hell in one string"),
("L04","pos",'dfhack.run_command({"reveal", "hell"})',"reveal table form"),
("L04","pos",'dfhack.run_command("revflood")',"revflood"),
("L04","pos",'local c = "reveal hell"\ndfhack.run_command(c)',"reveal via variable (command string assigned first)"),
("L04","neg",'local revealed = true',"revealed identifier"),
("L04","neg",'dfhack.run_command("unreveal")',"unreveal restores"),
("L04","neg",'-- reveal',"comment"),
# L05
("L05","pos",'dfhack.run_command("prospect all")',"prospect all"),
("L05","pos",'dfhack.run_command("prospect", "all")',"prospect table"),
("L05","pos",'dfhack.run_command("prospect  all")',"prospect two spaces"),
("L05","neg",'dfhack.run_command("prospect")',"prospect without all"),
("L05","neg",'local prospective = "all"',"identifier"),
# L06
("L06","pos",'item.flags.foreign = false',"foreign=false"),
("L06","pos",'it.flags.foreign=true',"foreign=true no spaces"),
("L06","pos",'for _,id in ipairs({1}) do df.item.find(id).flags.foreign=false end',"foreign one-liner"),
("L06","neg",'if item.flags.foreign == true then print(1) end',"comparison"),
("L06","neg",'local f = item.flags.foreign',"read"),
# L07
("L07","pos",'u.flags1.left = true',"left=true"),
("L07","pos",'u.flags2.left=true',"flags2.left"),
("L07","neg",'if u.flags1.left == true then end',"comparison"),
("L07","neg",'u.flags1.left = false',"left=false"),
# L08
("L08","pos",'u.pos.x = 10',"pos.x ="),
("L08","pos",'dfhack.run_command("teleport")',"teleport cmd"),
("L08","pos",'dfhack.units.setPos(u, 1,2,3)',"setPos"),
("L08","pos",'local border = u\nborder.pos.x = 5',"identifier containing 'order' (evades unless_line)"),
("L08","pos",'u.pos = {x=1,y=2,z=3}',"whole pos table assigned"),
("L08","neg",'if u.pos.x == 10 then end',"comparison"),
("L08","neg",'local o = df.squad_order_movest:new()\no.pos.x = 5',"squad order target"),
("L08","neg",'local teleporting_label = 1',"identifier teleporting_label"),
# L09
("L09","pos",'des.hidden = false',"hidden=false"),
("L09","pos",'df.global.world.map.block_index[0][0][0].designation[1][1].hidden=false',"designation hidden"),
("L09","neg",'if des.hidden == false then end',"comparison"),
("L09","neg",'local h = des.hidden',"read"),
# L10 (warn)
("L10","pos",'local tt = dfhack.maps.getTileType(1,2,3)',"getTileType without hidden check"),
("L10","pos",'local tt = dfhack.maps.getTileType(1,2,3)\nlocal x = other.hidden',"hidden elsewhere in file (rule disabled file-wide?)"),
("L10","neg",'local tt = dfhack.maps.getTileType(1,2,3)\nif dfhack.maps.getTileFlags(1,2,3).hidden then return end',"hidden check in file"),
("L10","neg",'local x = 1',"no tile read"),
# L11
("L11","pos",'plotinfo.equipment.work_weapons[1] = 5',"work_weapons index assign"),
("L11","pos",'work_weapons:insert("#", 5)',"insert"),
("L11","pos",'df.global.plotinfo.equipment.work_weapons:erase(0)',"erase"),
("L11","neg",'local n = #plotinfo.equipment.work_weapons',"read length"),
("L11","neg",'if work_weapons[1] == 3 then end',"comparison"),
# L12
("L12","pos",'bld.owner = u',"owner assign"),
("L12","pos",'dfhack.buildings.setOwner(b, u)',"setOwner"),
("L12","pos",'item.owner_id=3',"owner_id"),
("L12","neg",'if b.owner == u then end',"comparison"),
("L12","neg",'local o = b.owner',"read"),
# L13
("L13","pos",'if it.flags.foreign then it.flags.forbid = true end',"forbid foreign goods"),
("L13","neg",'it.flags.forbid = true -- trader goods',"comment mention only (comment stripped) -> must NOT fire"),
("L13","neg",'item.flags.forbid = true',"forbid own item"),
("L13","neg",'if item.flags.forbid == true then local trader = 1 end',"comparison"),
# L14
("L14","pos",'u.body.blood_count = 100',"blood_count"),
("L14","pos",'u.body.wounds:erase(0)',"wounds erase"),
("L14","pos",'u.body.wounds = {}',"wounds="),
("L14","neg",'local b = u.body.blood_count',"read"),
("L14","neg",'if u.body.blood_count >= 5 then end',"comparison >="),
("L14","neg",'if u.body.blood_count==5 then end',"comparison =="),
# L15
("L15","pos",'u.counters2.hunger_timer = 0',"hunger_timer"),
("L15","pos",'u.counters.sleepiness_timer=0',"sleepiness"),
("L15","pos",'u.counters2.thirst_timer = u.counters2.thirst_timer - 100',"thirst arithmetic"),
("L15","neg",'if u.counters2.hunger_timer > 5 then end',"read"),
("L15","neg",'local t = u.counters2.thirst_timer',"read"),
# L16
("L16","pos",'sk.rating = 10',"rating"),
("L16","pos",'sk.experience = 0',"experience"),
("L16","pos",'u.status.current_soul.skills[1] = x',"skills index assign"),
("L16","neg",'local r = sk.rating',"read"),
("L16","neg",'if sk.rating == 3 then end',"comparison"),
# L17
("L17","pos",'dfhack.maps.setTileType(1,2,3,4)',"setTileType"),
("L17","pos",'dfhack.run_command("tiletypes-here")',"tiletypes-here"),
("L17","pos",'blk.tiletype[1][1] = 5',"tiletype array assign"),
("L17","neg",'local tt = dfhack.maps.getTileType(1,2,3) -- hidden',"getTileType read"),
("L17","neg",'local tiletypes = {}',"identifier 'tiletypes' (false positive?)"),
# L18
("L18","pos",'des.flow_size = 7',"flow_size"),
("L18","pos",'des.liquid_type = 1',"liquid_type"),
("L18","pos",'dfhack.run_command("liquids")',"liquids"),
("L18","neg",'if des.flow_size > 0 then end',"read"),
("L18","neg",'local liquids = {}',"identifier 'liquids' (false positive?)"),
# L19
("L19","pos",'df.global.world.raws.items.all[0].x = 1',"raws assign"),
("L19","neg",'local r = df.global.world.raws.items.all',"read"),
("L19","neg",'if df.global.world.raws.x == 1 then end',"comparison"),
# L20
("L20","pos",'item.quality = 5',"quality"),
("L20","pos",'item:setQuality(5)',"setQuality"),
("L20","neg",'if item.quality == 5 then end',"comparison"),
("L20","neg",'local q = item.quality',"read"),
# L21
("L21","pos",'item.mat_type = 0',"item.mat_type"),
("L21","pos",'it.mat_index = 1',"it.mat_index"),
("L21","pos",'weapon.mat_type = 0',"variable not named item/it/itm"),
("L21","pos",'dfhack.items.setMaterial(i, 1, 2)',"setMaterial"),
("L21","neg",'if item.mat_type == 0 then end',"comparison"),
("L21","neg",'local j = job.mat_type',"read"),
# L22
("L22","pos",'item.stack_size = 100',"stack_size"),
("L22","pos",'item:setStackSize(5)',"setStackSize"),
("L22","neg",'if item.stack_size == 1 then end',"comparison"),
("L22","neg",'local s = item.stack_size',"read"),
# L23
("L23","pos",'u.flags1.dead = true',"dead"),
("L23","pos",'u.flags1.caged = false',"caged"),
("L23","pos",'u.flags2.killed=true',"killed"),
("L23","neg",'if u.flags1.dead then end',"read"),
("L23","neg",'if u.flags1.inactive == false then end',"comparison"),
# L24
("L24","pos",'dfhack.units.kill(u)',"units.kill"),
("L24","pos",'dfhack.run_command("exterminate")',"exterminate"),
("L24","pos",'dfhack.run_command("slayrace GOBLIN")',"slayrace"),
("L24","neg",'local kill_list = {}',"identifier"),
("L24","neg",'-- exterminate',"comment"),
# L25
("L25","pos",'dfhack.run_command("fastdwarf 1")',"fastdwarf"),
("L25","pos",'dfhack.run_command("full-heal")',"full-heal"),
("L25","pos",'dfhack.run_command("cleaners")',"cleaners"),
("L25","pos",'dfhack.run_command("regrass")',"regrass"),
("L25","neg",'local cleaners = {}',"identifier 'cleaners'"),
("L25","neg",'dfhack.run_command("deathcause")',"deathcause is read-only information"),
# L26
("L26","pos",'dfhack.run_command("gui/gm-editor")',"gm-editor"),
("L26","pos",'dfhack.run_command("gm-unit")',"gm-unit"),
("L26","neg",'-- gm-editor',"comment"),
("L26","neg",'local gm = 1',"identifier"),
# L27
("L27","pos",'u.civ_id = 5',"civ_id"),
("L27","pos",'u.hist_figure_id=-1',"hist_figure_id"),
("L27","neg",'if u.civ_id == df.global.plotinfo.civ_id then end',"comparison"),
("L27","neg",'local c = u.civ_id',"read"),
# L28 (warn)
("L28","pos",'local f = df.global.world.features.map_features',"world.features"),
("L28","pos",'local x = underground_region',"underground_region"),
("L28","neg",'local u = df.global.world.units.active',"units"),
("L28","neg",'local x = 1',"plain"),
# L29
("L29","pos",'dfhack.run_command("modtools/create-unit")',"modtools/create-unit"),
("L29","pos",'dfhack.run_command("create-unit", "GOBLIN")',"create-unit"),
("L29","neg",'local x = "create_unit_label"',"identifier-like"),
# L30
("L30","pos",'dfhack.run_command("changeitem")',"changeitem"),
("L30","pos",'dfhack.run_command("changetype")',"changetype"),
("L30","neg",'local changeLog = 1',"identifier"),
("L30","neg",'-- changeitem',"comment"),
]
